services:
  mysql:
    image: mysql:8.0
    container_name: sakila-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sakila
    volumes:
      - ./docker/init:/docker-entrypoint-initdb.d
